# Staging values for the shared fastapi-service chart
replicaCount: 1
namespace: "staging"

image:
  # TODO (nkapur): Push this into the helm chart
  repositoryName: "one_home"

  # TODO (nkapur): This would be updated by your CI/CD pipeline
  tag: "latest-arm64"  # v1.0.0-arm64

ingress:
  # TODO (nkapur): Push the construction of this into the helm chart
  host: "one-home.staging.navneetkapur.com"
  annotations: {}
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi